# Generated by Django 5.2.6 on 2026-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('bus_type', models.CharField(max_length=50)),
            ],
        ),
    ]
